version: 0.0
os: linux
files:
  - source: /
    destination: /app/
permissions:
  - object: /app/scripts/deploy.sh
    mode: 755
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
